app:
  - changed-files:
      - any-glob-to-any-file: "app/**"

frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**"

scripts:
  - changed-files:
      - any-glob-to-any-file: "scripts/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile"
          - "docker-compose.yml"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "requirements.txt"
          - ".env*"
